export const kits = [
  {
    id: "software-engineer",
    number: "01",
    title: "Software Engineer",
    subtitle: "Build a strong first impression.",
    experience: "0-1 years",
    level: "Early career",
    category: "Engineering",
    price: 200,
    color: "mint",
    icon: "Code2",
    label: "Start here",
    description:
      "Core CS, coding patterns, and the questions behind your first engineering role.",
    topics: [
      "Data structures",
      "OOP & databases",
      "Coding patterns",
      "Interview practice",
    ],
    questions: 50,
    pages: 28,
  },
  {
    id: "senior-software-engineer",
    number: "02",
    title: "Senior Software Engineer",
    subtitle: "Go beyond the right answer.",
    experience: "2-4 years",
    level: "Experienced",
    category: "Engineering",
    price: 400,
    color: "blue",
    icon: "Layers",
    label: "Go deeper",
    description:
      "Production decisions, backend trade-offs, and ownership at the next level.",
    topics: [
      "Concurrency",
      "API architecture",
      "Reliability",
      "Technical ownership",
    ],
    questions: 50,
    pages: 28,
  },
  {
    id: "ai-engineer",
    number: "03",
    title: "AI Engineer",
    subtitle: "From model to production.",
    experience: "Experienced",
    level: "Experienced",
    category: "AI & Data",
    price: 500,
    color: "lilac",
    icon: "BrainCircuit",
    label: "Applied AI",
    description:
      "ML foundations, LLM systems, evaluation, and responsible AI deployment.",
    topics: ["Machine learning", "LLMs & RAG", "Evaluation", "MLOps"],
    questions: 50,
    pages: 28,
  },
  {
    id: "system-design",
    number: "04",
    title: "System Design Round",
    subtitle: "Think clearly at scale.",
    experience: "All levels",
    level: "All levels",
    category: "System Design",
    price: 500,
    color: "peach",
    icon: "Network",
    label: "Think at scale",
    description:
      "Architecture prompts, capacity estimates, and decisions you can defend.",
    topics: [
      "Distributed systems",
      "Scaling patterns",
      "Case studies",
      "Trade-off analysis",
    ],
    questions: 50,
    pages: 28,
  },
  {
    id: "frontend-engineer",
    number: "05",
    title: "Frontend Engineer",
    subtitle: "Know what happens in the browser.",
    experience: "0-3 years",
    level: "Early career",
    category: "Engineering",
    price: 300,
    color: "yellow",
    icon: "PanelsTopLeft",
    label: "Browser to UI",
    description:
      "JavaScript, React, accessibility, and fast, resilient user experiences.",
    topics: ["JavaScript", "React", "Web performance", "Accessibility"],
    questions: 50,
    pages: 28,
  },
  {
    id: "backend-engineer",
    number: "06",
    title: "Backend Engineer",
    subtitle: "Build the systems behind the screen.",
    experience: "1-4 years",
    level: "Experienced",
    category: "Engineering",
    price: 350,
    color: "rose",
    icon: "Database",
    label: "Behind the API",
    description:
      "APIs, data modeling, security, and the operational side of backend work.",
    topics: ["API design", "SQL", "Security", "Operations"],
    questions: 50,
    pages: 28,
  },
];
export const money = (amount) =>
  new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(amount);
